# Define workflow name.
name: continuous-regression

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:
  

jobs:
  test:
    runs-on: ubuntu-latest
    name: test
    timeout-minutes: 30
    steps: 
      - name: Clone mo-nightly-regression Repo
        uses: actions/checkout@v2
        with:
          repository: aressu1985/mo-continuous-regression
          path: ./mo-nightly-regression
          ref: main
      - name: test
        run: |
          echo $GITHUB_WORKSPACE
          echo "$GITHUB_WORKSPACE"
          cd $GITHUB_WORKSPACE/mo-continuous-regression
          sed -i '/  LOAD:*/c\  LOAD: "$GITHUB_WORKSPACE\/mo-load-data\/report"' config.yml
          cat config.yml
          
