# Define workflow name.
name: continuous-regression

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:
  

jobs:
  bvt-linux-x86:
    runs-on: ubuntu-latest
    name: BVT Test on Ubuntu/x64
    timeout-minutes: 30
    
    steps:
      - name: checkout head
        uses: actions/checkout@v2
        with:
          path: ./head
          repository: matrixorigin/matrixone
          ref: main
      
      - name: Set up Go
        uses: ./head/.github/actions/setup_env

      - name: Build MatrixOne
        run: |
         cd $GITHUB_WORKSPACE/head
         commit_id=$(git rev-parse --short HEAD)
         echo $commit_id
         echo "commit_id="$commit_id >> $GITHUB_ENV
         echo '**'${{ env.commit_id }}
          
          
